# Generated by Django 3.0.2 on 2020-10-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('texto', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
