# Generated by Django 3.0.2 on 2020-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectotexto',
            name='proyecto',
            field=models.IntegerField(default=0),
        ),
    ]
