# Generated by Django 3.0.2 on 2020-11-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20201107_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectotexto',
            name='texto',
            field=models.TextField(),
        ),
    ]
