# Generated by Django 3.0.2 on 2020-11-07 18:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20201107_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectotexto',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
