# Generated by Django 3.0.2 on 2020-11-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
